apiVersion: v1
kind: ConfigMap
metadata:
  name: db-config
  namespace: fashion-app
data:
  POSTGRES_DB: postgres
  POSTGRES_USER: postgres
  primary.conf: |
    wal_level = replica
    max_wal_senders = 10
    max_replication_slots = 10
    hot_standby = on
  replica.conf: |
    hot_standby = on