apiVersion: v1
kind: ConfigMap
metadata:
  name: backend-config
  namespace: fashion-app
data:
  SPRING_PROFILES_ACTIVE: "prod"
  SPRING_DATASOURCE_URL: "jdbc:postgresql://postgres-service.fashion-app.svc.cluster.local:5432/postgres"