apiVersion: v1
kind: Service
metadata:
  name: backend-service
  namespace: fashion-app
spec:
  type: ClusterIP
  selector:
    app: fashion-backend
  ports:
  - port: 8080
    targetPort: 8080
    protocol: TCP